### ISSUE TITLE
ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by FluidDK** [tblaschke/reinvent#1]
I got error with gitpython=2.1.3 while trying to install it with "conda env create -f environment.yml" so I removed it from the file and install it directly with "pip install gitpython==2.1.3" from a Jupyer Notebook running from the conda reinvent environment and kernel. When I try to import or run the reinforce_model.py I get this error: ModuleNotFoundError: No module named 'gitdb.utils.compat'.

Do you know how I can proceed from here?
![Screenshot from 2020-06-14 11-49-26](https://user-images.githubusercontent.com/31069927/84583609-342bb200-ae35-11ea-8456-3f64338b75cd.png)

**Comment by tblaschke** [comment]
Yes you are right. It seems some dependencies got updated and now code to obtain the metadata from the git repo does not work anymore.

I will have a look into this in the next days. What reinforce_model is trying to do, is to obtain the current git commit hash and save it in the metadata.json. As I've never really used  this feature I guess I will just remove it and not try to save the current git hash in the metadata.

**Comment by tblaschke** [comment]
As a quick workaround: Modify your local version of the reinforce_model and delete the `import git` at line 11. Then modify the function `get_commit_hash()` at line 19 to return an empty string. E.g.: 

`def get_commit_hash():
    return ""`
